package cz.ispadmin.entities;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "service_desk", catalog = "ropr"
)
public class ServiceDesk implements java.io.Serializable {

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  private Integer id;
  
  @ManyToOne(cascade = CascadeType.ALL)
  @JoinColumn(name="userId")
  private Users user;
  
  @Size(min = 2, max = 20)
  private String message;

  public ServiceDesk() {
    
  }

  public ServiceDesk(String message) {
    this.message = message;
  }

  public void setData(ServiceDesk desk) {
    this.message = desk.getMessage();
  }

  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Users getUser() {
    return user;
  }

  public void setUser(Users user) {
    this.user = user;
  }

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

}
